import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar.js/Navbar";
import { SearchProvider } from "./contexts/SearchContext";
import { AuthProvider } from "./contexts/AuthContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <SearchProvider>
            <Navbar/>
            {children}
          </SearchProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
